export const dataInfoStore = [
    {
        title: "Tu tienda de suplementos y nutrición deportiva",
        description: "Los suplementos deportivos constituyen en la actualidad uno de los elementos de alimentación más importantes que debe llevar a cabo cualquier atleta o deportista. Tal y como su nombre indica, sirven de gran ayuda para complementar la dieta, equilibrarla con ciertas sustancias y evitar así posibles carencias nutricionales que pueden surgir con el desgaste físico que se produce en el entrenamiento o la práctica deportiva. "
    },
    {
        title: "¿Qué son los suplementos deportivos?",
        description: "En líneas generales, los suplementos deportivos son alimentos concentrados que mantienen sus propiedades nutritivas más importantes después incluso de la manipulación de su estado original.Una manipulación con la se pueden aumentar las propiedades nutritivas del propio alimento en sí o eliminar aquellas que sean menos deseables para el entrenamiento y la dieta del deportista.Los suplementos que podemos encontrar en la actualidad suelen mejorar notablemente el rendimiento atlético. Por lo general, incluyen un alto aporte de vitaminas, minerales, aminoácidos, hierbas o cualquier concentración, extracto o combinación de todas estas sustancias.Son, por tanto, suplementos dietéticos o alimenticios que se pueden comprar en la tienda suplementos deportivos.De todos es sabido que el cuidado de la nutrición es esencial en la práctica deportiva para mejorar el rendimiento y la recuperación del organismo tras el esfuerzo. La alta carga de trabajo en un entrenamiento o en el deporte en sí requiere de una energía y una serie de nutrientes que en muchas ocasiones no se consiguen del todo mediante una dieta equilibrada."
    },
    {
        title: "Ventajas y beneficios de los suplementos deportivos",
        description: "Tal y como hemos comentado, los suplementos deportivos cubren diferentes necesidades nutricionales. Dependiendo de la intensidad y la frecuencia de la práctica deportiva o el entrenamiento, necesitaremos recurrir a estos suplementos para paliar la pérdida de nutrientes, proteínas, aminoácidos, etc.Por otro lado, los suplementos deportivos proporcionan una ayuda fisiológica directa. Uno de sus principales aportes es el aumento del rendimiento, pero también son muy beneficiosos para aumentar la masa muscular o para la recuperación posterior tras el ejercicio físico.Al mismo tiempo, los suplementos deportivos también pueden ser capaces de acelerar el proceso de pérdida de grasa (los quemadores de grasa), mejorando el estado general de alerta en el organismo. Además, son los encargados de aumentar la oxidación de grasas y evitar la bajada del gasto metabólico.Por último, hay que recordar que en ningún caso debemos basar nuestra dieta única y exclusivamente en la toma de suplementos deportivos, pero sí podemos hacer lo contrario. La dieta de cualquier deportista debe ser equilibrada, rica en proteínas, hidratos de carbono y grasas."
    }
]